name: DevOps Automation Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  # Job 1: Verify Code Quality (CI)
  code-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Lint and Test Code
      run: |
        pip install -r requirements.txt
        python -m py_compile app.py

  # Job 2: Build & Publish to Docker Hub (CD)
  build-and-push:
    runs-on: ubuntu-latest
    needs: code-test
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          docker.io/mizanolinko/prod-app:latest
          docker.io/mizanolinko/prod-app:${{ github.sha }}

  # Job 3: Pull & Run the new container on AWS
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push # Only run if the build and push succeeds!

    steps:
    - name: SSH into EC2 and Deploy
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 2222
        script: |
          # Stop the old running container (ignore error if it doesn't exist yet)
          sudo docker stop prod-cloud-app || true
          sudo docker rm prod-cloud-app || true
          
          # Pull the latest image we just compiled
          sudo docker pull mizanolinko/prod-app:latest
          
          # Run the fresh container version on host port 8080
          sudo docker run -d --name prod-cloud-app -p 8080:8080 --network portfolio-network --restart always mizanolinko/prod-app:latest